server:
  port: 18001

game:
  config:
    debug: false
  server:
    check-secret: false # 作为服务端时，是否加密
  client:
    check-secret: false # 作为服务端时，是否加密


spring:
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Feign 等会存在重复定义的服务

  webflux:
    webflux:
      compress:
        enabled: true
        min-response-size: 10240 # 设置最小响应大小（字节）
    websocket:
      max-frame-payload-length: 1048576  # 设置最大帧长度为 1MB

#  data:
#    mongodb:
#      uri: mongodb://admin:123456@192.168.1.3:27017/?authSource=admin
#      database: YourDatabase

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/slgGameDB?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&useServerPreparedStmts=false&rewriteBatchedStatements=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai"
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  druid:
    filters: stat,wall,log4j2
    max-active: 20
    initial-size: 1
    max-wait: 60000
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20

  data:
    redis:
      host: 192.168.1.3
      port: 6379
      database: 6

  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true  # 开启/关闭驼峰命名转换
    global-config:
      db-column-underline: true  # 开启/关闭数据库字段下划线命名
      refresh-mapper: true
    mapper-locations: classpath:/mapper/**/*.xml
    typeAliasesPackage: com.yb.yff.game.data.entitys.*.*

#logging:
#  level:
#    org.springframework.web.reactive: DEBUG
#    reactor.netty: DEBUG
#    org.springframework.core.codec: DEBUG
#    org.springframework.http.server.reactive: DEBUG
