server:
  port: 18004

#spring:
#  main:
#    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
#    web-application-type: none

game:
  # 其它业务服务信息，临时配置，后期要改为由负载均衡分配
  servers:
    # 游戏逻辑服务
    games:
      - nodeName: slgServer
        node: ws//192.168.1.3:18001
    # 聊天服务
    chats:
      - nodeName: chatServer
        node: ws//192.168.1.3:18002
    # 账户服务
    accounts:
      - nodeName: accountServer
        node: http://192.168.1.3:18003
