server:
  port: 18004

spring:
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
#    web-application-type: none
  # 开启响应压缩
  webflux:
    compress:
      enabled: true
      min-response-size: 1024 # 设置最小响应大小（字节）

game:
  server:
    check-secret: true # 作为服务端时，是否加密
  client:
    check-secret: false # 作为服务端时，是否加密

  # 其它业务服务信息，临时配置，后期要改为由负载均衡分配
  servers:
    # 游戏逻辑服务
    games:
      - nodeName: slg
        node: ws://192.168.1.3:18001/ws
    # 聊天服务
    chats:
      - nodeName: chat
        node: ws://192.168.1.3:18002/ws
    # 账户服务
    accounts:
      - nodeName: account
        node: http://192.168.1.3:18003


logging:
  level:
    reactor:
      netty=DEBUG: